### ISSUE TITLE
FreeCAD homepage.po

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#215]
Main page:

I have marked the passages that require attention

![image](https://user-images.githubusercontent.com/39754351/234948093-299f8e80-7bdc-4bd6-9e52-7c92d9f9aca5.png)

![image](https://user-images.githubusercontent.com/39754351/234948457-eefb6f4a-6856-4dea-94a8-aa3a09ddd466.png)

Page features:

![image](https://user-images.githubusercontent.com/39754351/234949701-4a30f290-510f-4281-9990-388758adb4a1.png)

Page Donating and sponsoring:

![image](https://user-images.githubusercontent.com/39754351/234950802-54cedcf1-872d-4733-b9bf-d442db0d4f00.png)

**Comment by chennes** [comment]
I just uploaded a new version of the `homepage.po` file with the website as it stands right now. I did not pull translations down yet.

**Comment by yorikvanhavre** [comment]
I just merged the latest translations from crowdin.
AFAICS (I just checked a few...) these strings have all been changed and need to be retranslated...

**Comment by kaktusus** [comment]
There is a big improvement however I still see some minor problems:

image

Page features:

![image](https://user-images.githubusercontent.com/39754351/235304984-f1f5debd-ce9e-451c-bb10-f16da5edcb4a.png)

the size and position of these graphics differ from the others on the site

![image](https://user-images.githubusercontent.com/39754351/235305685-55a072a0-9673-45d0-90b1-0391a8119f4e.png)

All `submit` buttons on the Donating and sponsorship page:

![image](https://user-images.githubusercontent.com/39754351/235305556-129346f4-39e3-46e3-a86d-3e5bfdc91efb.png)

**Comment by kaktusus** [comment]
Incorrect display of graphics was caused by a missing closing tag in one of the translated strings.

**Comment by chennes** [comment]
OK, "current stable release" and "Submit" should be available on CrowdIn now.

**Comment by kaktusus** [comment]
I can't wait for the website to be updated.
I expect I don't remember when it looked as good as it may look this time!

**Comment by chennes** [comment]
I just sync'ed the website with CrowdIn. I am closing this issue, if particular problems occur please open new tickets for each and I will try to resolve ASAP.

**Comment by kaktusus** [comment]
The translated page looks perfect.
